config/routes.rb
Rails.application.routes.draw do

  root "honest#index"
  get "/public" => "honest#public"
  get "/how" => "honest#how"
  get "/contact" => "honest#contact"

  get "/users" => "users#index"
  post "/users" => "users#create"
  get "/users/new" => "users#new"
  get "/users/:id/edit" => "users#edit", as: :edit_user
  get "/users/:id" => "users#show", as: :user
  patch "/users/:id" => "users#update"
  delete "/users/:id" => "users#destroy"

  get "/messages" => "messages#index"
  post "/messages" => "messages#create"
  get "/messages/new" => "messages#new"
  get "/messages/:id/edit" => "messages#edit", as: :edit_message
  get "/messages/:id" => "messages#show", as: :message
  patch "/messages/:id" => "messages#update"
  delete "/messages/:id" => "messages#destroy"

  get "/messages/:message_id/addresses" => "addresses#index", as: :message_addresses
  post "/messages/:message_id/addresses" => "addresses#create"
  get "/messages/:message_id/addresses/new" => "addresses#new", as: :new_message_address
  get "/messages/:message_id/addresses/:id/edit" => "addresses#edit", as: :edit_address
  get "/messages/:message_id/addresses/:id" => "addresses#show", as: :message_address
  patch "/messages/:message_id/addresses/:id" => "addresses#update"
  delete "/messages/:message_id/addresses/:id" => "addresses#destroy"

  

  get '/login' => 'sessions#new', as: :sign_up
  post '/login' => 'sessions#create', as: :sign_in
  delete '/logout' => 'sessions#destroy', as: :sign_out

  get "/charges" => "charges#index", as: :charges
  post "/charges" => "charges#create"
  get "/charges/new" => "charges#new", as: :new_charge
  get "/charges/:id/edit" => "charges#edit", as: :edit_charge
  get "/charges/:id" => "charges#show", as: :charge
  get "/charges/:id" => "charges#update"
  put "/charges/:id" => "charges#update"
  delete "/charges/:id" => "charges#destroy"

end

app/models/address.rb
class Address < ActiveRecord::Base
	belongs_to :message

	validates :address_1, presence: true
	validates :city, presence: true
	validates :state, presence: true
	validates :zip_code, presence: true
end

app/models/message.rb
class Message < ActiveRecord::Base
	belongs_to :user
	has_many :addresses

	validates :to_name, presence: true
	validates :msg, presence: true, length: {in: 8..300}
end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :messages
	
	has_secure_password

	validates :first_name, presence: true
	validates :last_name, presence: true
  	validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  	validates :password, presence: true, length: { in: 6..20 }
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  
  before_action :authorized?

  def index

  	@addresses = get_message.addresses.all
    @address_count = @addresses.count
    @message = get_message

  end



  def new

  	@address = get_message.addresses.build
  
  end



  def create
    @address = get_message.addresses.build(address_params)
  	
    #captures message_id when adding address
    # @address.message = Message.find(params[:id])
  	
  	if @address.save
      redirect_to message_addresses_path
  	else
      flash.now[:error] = @address.errors.full_messages
      render "new"
    end

  end



  def show

  	@address = get_message.addresses.find(params[:id])

    if @address.message.user_id != current_user.id
      redirect_to messages_path
    end

  end



  def edit

  	@address = get_message.addresses.find(params[:id])

    if @address.message.user_id != current_user.id
      redirect_to messages_path
    end

  end



  def update

  	@address = get_message.addresses.find(params[:id])

  	if @address.update(address_params)
  		redirect_to message_address_path
  	else
  		render "edit"
  	end
  
  end



  def destroy

  	@address = get_message.addresses.find(params[:id])
  	@address.destroy
  	redirect_to message_addresses_path

  end



private

	def address_params
		params.require(:address).permit(:address_1, :address_2, :city, :state, :zip_code)
	end

  def get_message
    @message = Message.find(params[:message_id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  	protect_from_forgery with: :exception

	include SessionsHelper

	def authorized?
		redirect_to sign_in_path unless current_user
	end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

	def new
	end

	def create
	  # Amount in cents
	  @amount = 300

	  customer = Stripe::Customer.create(
	    :email => 'example@stripe.com',
	    :card  => params[:stripeToken]
	  )

	  charge = Stripe::Charge.create(
	    :customer    => customer.id,
	    :amount      => @amount,
	    :description => 'Rails Stripe customer',
	    :currency    => 'usd'
	  )

	rescue Stripe::CardError => e
	  flash[:error] = e.message
	  redirect_to charges_path
	end
	
end

app/controllers/honest_controller.rb
class HonestController < ApplicationController
  
  def index
  end

  def how
  end

  def public
  	@messages = Message.where(is_public: true)
  end

  def contact
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

	before_action :authorized?

	def index
		@messages = get_user_message if current_user
		@message_count = @messages.count
	end

	def new
		@message = Message.new
	end

	def create
		@message = Message.new(message_params)
 		#captures user_id when creating message		
 		@message.user_id = current_user.id if current_user 

		if @message.save
			redirect_to @message
		else
			flash.now[:error] = @message.errors.full_messages
  			render "new"
		end
	end	

	def show
		@message = Message.find(params[:id])
		redirect_to public_path unless @message.user == current_user
	end

	def edit
		@message = Message.find(params[:id])
		redirect_to public_path unless @message.user == current_user
	end

	def update
		@message = Message.find(params[:id])

		if @message.update(message_params)
			redirect_to @message
		else
			flash.now[:error] = @message.errors.full_messages
			render "edit"
		end
	end

	def destroy
		@message = Message.find(params[:id])
		@message.destroy
	 
		redirect_to messages_path
	end


private

	def message_params
		params.require(:message).permit(:to_name, :msg, :is_public, :user_id)
	end

	def get_user_message
		 Message.where(user_id: current_user.id)
	end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	
	def new
		redirect_to messages_path if current_user
	end

	def show
	end

	def create
	
		user = User.find_by(email: params[:login][:email])

		if user && user.authenticate(params[:login][:password])
			#log them in (set a cookie)
			session[:user_id] = user.id.to_s
			redirect_to messages_path
		else
			render :new
		end
	end

	def destroy
		if session['auth']
	    	session['auth'] = nil
	    else
	    	session.delete(:user_id)
	    end
	    redirect_to sign_in_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :authorized?, except: [:new, :create]

  def index
  	@users = User.all
    redirect_to messages_path unless current_user.id == 1
  end

  def new
  	@user = User.new
    redirect_to messages_path if current_user
  end

  def create
	@user = User.new(user_params)
  	if @user.save
      flash[:notice] = "Thank you for signing up!"
      session[:user_id] = @user.id.to_s
  		redirect_to how_path
  	else
      flash.now[:error] = @user.errors.full_messages
  		render :new
  	end
  end

  def show
  	@user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user
    else
      render "edit"
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to users_path
  end

private
	def user_params
		params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
	end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/honest_helper.rb
module HonestHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def current_user
  		@current_user ||= User.find_by(id: session[:user_id])
	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/addresses/edit.html.erb
<h1>Edit this address for your message to <%= @address.message.to_name %> </h1>
<%= render "layouts/addresses_form" %>

app/views/addresses/index.html.erb
<h1>You have <%= pluralize(@address_count, "address") %> for your message to <%= @message.to_name %></h1>

	<% @addresses.each do |address| %>
	<address>
		<p class="lead">Message for <strong><%= address.message.to_name %></strong></p>
		<hr>
		<%= address.address_1 %><br>
		<%= address.city %>, <%= address.state.upcase %> <%= address.zip_code %>
		<hr>
		<%= link_to 'Delete', message_address_path(@message, address),
              method: :delete,
              data: { confirm: 'Are you sure?' }, 
              class: "btn btn-danger" %>
        <%= link_to 'Edit', edit_address_path(@message, address), class: "btn btn-warning" %> 
		<%= link_to 'View details', message_address_path(@message, address), class: "btn btn-default" %>	
		<%= link_to 'Send $3', new_charge_path, class: "btn btn-success" %> 
	</address>
	<% end %>
    <%= link_to 'Add an address', new_message_address_path(@message), class: "btn btn-success btn-lg btn-block" %>
    <%= link_to 'Go back to your message', message_path(@message), class: "btn btn-default btn-lg btn-block" %>

app/views/addresses/new.html.erb
<h1>Add new address for your message to <%= @address.message.to_name %> </h1>
<%= render "layouts/addresses_form" %>

app/views/addresses/show.html.erb
<h1>This is 1 of <%= pluralize(@address.message.addresses.count, "address") %> you have for your message to <%= @address.message.to_name %></h1>

<address>
	<p><strong><%= @address.message.to_name %></strong></p>
	<%= @address.address_1 %><br>
	<%= @address.city %>, 
	<%= @address.state.upcase %> 
	<%= @address.zip_code %>
	<hr>
	<p class="lead"><%= @address.message.msg %></p>

</address>

<%= link_to 'Delete', message_address_path,
      method: :delete,
      data: { confirm: 'Are you sure?' }, 
      class: "btn btn-danger" %>
<%= link_to 'Edit', edit_address_path, class: "btn btn-warning" %> 
<%= link_to 'Back to addresses', message_addresses_path(@message), class: "btn btn-default" %>	
<%= link_to 'Send $3', new_charge_path, class: "btn btn-success" %>

app/views/charges/create.html.erb
<h1>Thank you! Your <strong>$3.00</strong> payment has been processed.</h1>
<%= link_to "Back to messages", messages_path, class: "btn btn-default btn-lg" %>

app/views/charges/new.html.erb
<h1>Checkout</h1>

<%= form_tag charges_path do %>
  <article>
    <label class="amount">
      <span>Amount: $3.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Send my card"
          data-amount="300"></script>
<% end %>

app/views/honest/_sign_in_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Honestly</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
<!--       <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul> -->
<!--       <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">how it works</a></li>
        <li><a href="#">pricing</a></li>
        <li><a href="#">contact</a></li>
        <li><a href="#">sign in</a>
        <!-- use dropdown below for during signed-in state -->
<!--         <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Sign In <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li> -->
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/honest/contact.html.erb
<h1>Contact us</h1>

<div class="container">

	<div class="row">
	  <div class="col-md-6 col-md-offset-3">
		<dl class="dl-horizontal">

			<dt><span class="glyphicon glyphicon-map-marker lead" aria-hidden="true"></span></dt>
			<dd><p class="lead">
				<strong>Honestly</strong><br>
				WDI-16<br>
				1520 2nd St<br>
				Santa Monica, CA 90401<br></p></dd>

			<dt><span class="glyphicon glyphicon-envelope lead" aria-hidden="true"></span></dt>
			<dd><p class="lead">hello@simplyhonest.me</p></dd>

		</dl>
	  </div>
	</div>

</div>

app/views/honest/how.html.erb
<h1>How does this work?</h1>

<p class="lead"><strong>Simple. Just tell us what you truly feel about something or someone, and we'll sign a card with your message and send it for you</strong>. You keep your identity to yourself, and we make things better, one real and honest message at a time.</p>
<p class="lead">However, there is one simple rule that we need you to follow, <strong>be responsible</strong>.</p>
<p class="lead">It is easy to send messages of hate, or shame or harass someone with a concealed identity. We are not here for that. We're here to help you send across your message, which you wouldn't have the courage to say in person.</p><br>
<hr>
<blockquote class="blockquote-reverse">
  <p>We have the opportunity to do whatever we want through the Internet. Unfortunately, a lot of people choose to do the stupid ones.</p>
  <footer><cite title="Source Title">An Internet user</cite></footer>
</blockquote>
<hr>
<br>
<h2><strong><em>How much does it cost?</em></strong></h2>
<p class="lead">It costs $3 per card.</p>
<h2><strong><em>How are you going to send the card?</em></strong></h2>
<p class="lead">We'll send the card via the U.S. Postal Service. This means that we cannot gurantee the time of delivery.</p>
<h2><strong><em>Can I have a card sent to a foreign address?</em></strong></h2>
<p class="lead">No. We can only send cards to address within the United States.</p>
<h2><strong><em>Is there a limit on what I can write?</em></strong></h2>
<p class="lead">Yes. You have up to 300 characters to use when writing your message.</p>
<h2><strong><em>What if I really want to make things better, but I'm so upset right now. Can I send a card with an inappropriate language?</em></strong></h2>
<p class="lead">We totally feel you. That is why you can write your heart out for free when you create an account. Once your emotions have settled down, you can clean up your message and then we can send it for you. That is if you still need to. Sometimes, you just need to let it out and write it down. It helps a lot. Trust us, we know!</p>
<h2><strong><em>Will the whole world see my messages?</em></strong></h2>
<p class="lead">No. However, you can choose to make your message visible to to public.</p>
<h2><strong><em>Why do I need to use your website if I can just write it in a piece of paper or in my email?</em></strong></h2>
<p class="lead">Honestly, you don't need to. However, we can help you keep your identity when writing your true message.</p>
<br>
<p><a class="btn btn-success btn-lg btn-block" href="/messages" role="button"><strong>Got it. I'm ready!</strong></a></p>

app/views/honest/index.html.erb
<div class="msg-box">
	<%= image_tag "honestly.png" %>
	<p><a class="btn btn-primary btn-lg" href="/how" role="button">Learn more</a></p>
</div>

app/views/honest/public.html.erb
<h1>Here are some real messages from our users.</h1>
	
	<div class="container-fluid">

		<div class="row">
    	
		<% @messages.each do |message| %>

            <div class="col-md-2">
              <h4><%= message.to_name %></h4>
              <p><%= message.msg %></p>
              <% if message.user == current_user %>
              	<p><%= link_to 'View details', message_path(message), class: "btn btn-default" %> </p>
              <% end %>
	        </div><!--/.col-xs-4-->

        <% end %>

        </div><!--/row-->

	</div><!-- /container -->

app/views/layouts/_addresses_form.html.erb
<%= form_for [@address.message, @address], :html => {:class => "form-signin"}  do |f| %>
 
	<div>
	    <%= f.label "Street" %>
	    <%= f.text_field :address_1, class: "form-control", :autofocus => true %>
  	</div>
 
	<div>
	    <%= f.label :city %>
	    <%= f.text_field :city, class: "form-control" %>
  	</div>

	<div>
	    <%= f.label :state %>
	    <%= f.text_field :state, class: "form-control" %>
  	</div>

  	<div>
	    <%= f.label :zip_code %>
	    <%= f.text_field :zip_code, class: "form-control" %>
  	</div>

  	<br>
  	<div>
    	<%= f.submit class: "btn btn-lg btn-success btn-block"%> 
    	<%= link_to "Cancel", message_addresses_path, class: "btn btn-lg btn-danger btn-block"%>
  	</div>
 
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" id="brand" href="/">Honestly</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-right">
        <li><a href="/how">how it works</a></li>
        <li><a href="/public">messages</a></li>
        <li><a href="/contact">contact</a></li>
        <!-- use dropdown below for during signed-in state -->        
        <% if current_user %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> Hello, <%= current_user.first_name %> <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="/messages">My messages</a></li>
            <li><a data-method="delete" href="/logout">Log out</a></li>
          </ul>
        </li>
        <% else %>
        <!-- use dropdown below for during signed-out state -->
        <li><a href="/login">sign in</a></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_messages_form.html.erb
<%= form_for @message, :html => {:class => "form-horizontal"} do |f| %>
 
<div class="msg-box">
	<div class="form-group">
	    <%= f.label "To:", class: "col-sm-2 control-label" %>
	    <div class="col-sm-6">
	    	<%= f.text_field :to_name, class: "form-control", placeholder: "Name", :autofocus => true %>
	    </div>
  	</div>
 
	<div class="form-group">
	    <%= f.label "Message:", class: "col-sm-2 control-label" %>
	    <div class="col-sm-6">
	    	<%= f.text_area :msg, class: "form-control", rows: "5", placeholder: "Keep it real, short and clean. Up to 300 characters." %>
	    </div>
	</div>


	<div class="form-group">
    	<div class="col-sm-offset-2 col-sm-6">
      		<div class="checkbox">
        		<label>
        			<%= f.check_box :is_public %> <%= f.label "Check this box if you want to make this message public." %>
        		</label>
      		</div>
    	</div>
  	</div>

	<div class="form-group">
	    <div class="col-sm-offset-2 col-sm-6">
	   	   	<%= f.submit class: "btn btn-lg btn-success btn-block" %>
  		</div>
  	</div>

	<div class="form-group">
    	<div class="col-sm-offset-2 col-sm-6">
   	   		<%= link_to 'Cancel', messages_path, class: "btn btn-lg btn-danger btn-block" %>
		</div>
	</div>

</div>

 
<% end %>

app/views/layouts/_sign_up.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <div>
    <%= f.label :first_name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/layouts/_users_form.html.erb
<%= form_for @user, :html => {:class => "form-signin"} do |f| %>

  <div>
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: "form-control" %>
  </div>

  <div>
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: "form-control" %>
  </div>  

  <div>
    <%= f.label :email %>
    <%= f.text_field :email, class: "form-control" %>
  </div>

  <div>
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control" %>
  </div>
  
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
  </div>
  
  <br>
  <div>
    <%= f.submit class: "btn btn-lg btn-default btn-block" %>
  </div>

<% end %>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>HonestlyApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
	<div class="container-fluid">

	<!-- navbar login header -->
		<%= render 'layouts/header' %>
	    
	    <div class="container-fluid">
	    	
	    	<!-- error notification loop -->
		    <% if flash[:error] %>
		      <% flash[:error].each do |message| %>
		        <div class="alert alert-danger" role="alert"><%= message %></div>
		      <% end %>
		    <% end %>

		    <!-- message notifications -->
		    <% if flash[:notice] %>
		      <div class="alert alert-info" role="alert"><%= flash[:notice] %></div>
		    <% end %>
  			<%= yield %>

			<hr>
			<%= params %>
			<hr>

	    </div> <!-- content wrapper -->

	</div><!-- main container -->

</body>
</html>

app/views/messages/index.html.erb
<h1>You currently have <%= pluralize(@message_count, "message") %> in your account</h1>
	
	<div class="container-fluid">

		<div class="row">
    	
      <% @messages.each do |message| %> 
		  <div class="panel panel-default">
        <div class="panel-heading">
          <h2 class="panel-title">Message for 
            <%= message.to_name %> 
            <% if message.is_public %>
            <span class="badge">Public</span>
            <% end %>
          </h2>
         </div>
        <div class="panel-body">
            <%= message.msg %>
            <br><hr>
            <% if message.user == current_user %>
              <%= link_to 'View details', message_path(message), class: "btn btn-default" %>
            <% end %>
        </div>
      </div>
      <% end %>
      <%= link_to 'Create a new message', messages_new_path, class: "btn btn-success btn-lg btn-block" %>

    </div><!--/row-->
        
	</div><!-- /container -->

app/views/messages/show.html.erb
<h1>This is your message to <%= @message.to_name %></h1>

<div class="message-container">
	<div class="card">

		<!-- front face -->
		<div class="front face">
			<div class="panel panel-primary">
		        <div class="panel-heading">
		          <h3 class="panel-title">
		            <% if @message.is_public %>
		            	<span class="tab-space"></span><span class="badge">Public</span>
		            <% end %>
		          </h3>
		        </div>
		        <div class="panel-body">
		            <p class="lead"><%= @message.msg %></p>
		            <br><hr>
		              Send a card for this message?
		        </div>
      		</div>
	  	</div>


	  	<!-- back face -->
	  	<div class="back face">
			<div class="panel panel-info">
				<div class="panel-heading">
					<h3 class="panel-title">
						This message has <%= pluralize(@message.addresses.count, "address") %>
					</h3>
				</div>
				<div class="panel-body">
					<% @message.addresses.first(2).each do |address| %>
						<address >
							<%= address.address_1 %><br>
							<%= address.city %>, <%= address.state.upcase %> <%= address.zip_code %><br><br>
							<%= link_to "Send to this address $3", message_address_path(@message, address), class: "btn btn-success btn-xs" %>	
						</address>
					<% end %>
					<hr>
					<% if @message.addresses.count == 0 %>
					<%= link_to 'Add an address', new_message_address_path(@message), class: "btn btn-success btn-lg btn-block" %>
					<% end %>
					<% if @message.addresses.count > 0 %>
					<%= link_to 'Go to addresses page', message_addresses_path(@message), class: "btn btn-default btn-lg btn-block" %>
					<% end %>
				</div>
			</div>		  
		</div>
	</div>
</div>
<br>

<div class="msg-box">
    	<div>
   	   		<%= link_to "Delete", message_path(@message),
              method: :delete,
              data: { confirm: "Are you sure? If you have an address linked to this message, please click 'CANCEL' and delete it first." }, 
              class: "btn btn-danger" %>
   	   		<%= link_to "Edit", edit_message_path(@message), class: "btn btn-warning" %>
   	   		<%= link_to 'Back to messages', messages_path, class: "btn btn-default" %>
		</div>
</div>

app/views/users/index.html.erb
<h1>All Users</h1>

<% @users.each do |user| %>
<ul>
	<li><%= user.first_name.capitalize %> <%= user.last_name.capitalize %> <%= link_to "Show", user_path(user) %> <%= link_to "Edit", edit_user_path(user) %> <%= link_to "Delete", user_path(user),
		method: :delete,
		data: {confirm: "Are you sure?"} %></li>
</ul>

	

<% end %>

app/views/users/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to "Edit", edit_user_path(@user) %> 
<%= link_to "Delete", user_path(@user),
	method: :delete,
	data: { confirm: "Are you sure?" } %>
<%= link_to "Back", users_path %>